version: '3.1'

services:
  devmachine: &default
    build: ./build1
    image: gwjjeff/devbase
    environment:
      POWER_USER: jeff
      JAVA_HOME: /opt/jdk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop/hadoop-2.7.4:/opt/hadoop-2.7.4:ro
      - ./entryfiles/_etc/resolv.conf:/etc/resolv.conf
      - ./data:/data

  pseudo:
    <<: *default
    environment:
      POWER_USER: pseudo
    ports:
      - "20122:22"

  master:
    <<: *default
    environment:
      POWER_USER: hdfs
  
  slave:
    <<: *default
    environment:
      POWER_USER: hdfs

  dnsmasq:
    image: jpillora/dnsmasq
    environment:
      USER: jeff
      PASS: test
    volumes:
      - ./entryfiles/_etc/dnsmasq.conf:/etc/dnsmasq.conf
      - ./entryfiles/_etc/dnsmasq.hosts:/etc/dnsmasq.hosts