version: '3.1'

services:
  devmachine: &default
    build: ./build1
    image: gwjjeff/devbase
    environment:
      POWER_USER: jeff
      JAVA_HOME: /opt/jdk
    volumes:
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop:/opt/hadoop:ro

  node1:
    <<: *default
    environment:
      POWER_USER: hdfs
  node2:
    <<: *default
    environment:
      POWER_USER: yarn