version: '3.1'

services:
  devmachine: &default
    build: ./build1
    image: gwjjeff/devbase
    environment:
      POWER_USER: jeff
      JAVA_HOME: /opt/jdk
    volumes:
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop/hadoop-2.7.4:/opt/hadoop-2.7.4:ro
      - ./data:/data

  node1:
    <<: *default
    environment:
      POWER_USER: pseudo
    ports:
      - "20122:22"

  master1:
    <<: *default
    environment:
      POWER_USER: hdfs
    volumes:
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop/hadoop-2.7.4:/opt/hadoop-2.7.4:ro
      - ./data/master1:/data
  
  slave1:
    <<: *default
    environment:
      POWER_USER: hdfs
    volumes:
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop/hadoop-2.7.4:/opt/hadoop-2.7.4:ro
      - ./data/slave1:/data
  
  slave2:
    <<: *default
    environment:
      POWER_USER: hdfs
    volumes:
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop/hadoop-2.7.4:/opt/hadoop-2.7.4:ro
      - ./data/slave2:/data
  
  slave3:
    <<: *default
    environment:
      POWER_USER: hdfs
    volumes:
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop/hadoop-2.7.4:/opt/hadoop-2.7.4:ro
      - ./data/slave3:/data
  