version: '3.1'

services:
  devbase: &default
    build: ./build1
    image: gwjjeff/devbase
    domainname: polar.local
    environment:
      POWER_USER: jeff
      JAVA_HOME: /opt/jdk
    volumes:
      - ./entryfiles:/root/entryfiles:ro
      - ./entryfiles/_etc/supervisor/supervisord.d:/etc/supervisor/supervisord.d:ro
      - ./entryfiles/_etc/profile.d/misc.sh:/etc/profile.d/misc.sh:ro
      - /opt/jdk:/opt/jdk:ro
      - /home/jeff/bench/java/hadoop/hadoop-2.7.4:/opt/hadoop-2.7.4:ro
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nw1
      - nw2

networks:
  nw1:
  nw2:
